# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: badbf4f4f5e7f6a69da90cf0a65a2d1f55e69aab3901578536d3a2b0e1abb0f4aafacd6f4c6cda40b399cdc75814207d330e143c3e2bbc4af23fd5853574086d

test:
  secret_key_base: 7be1636292ec2703397419556e57af8fab9b909a4830818ebc05a5ed41f0f699c69fa6c5650de4f7de2d101e288535f164d6c5425665710a3d512b1cc2875489

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
